#' An implementation of the step function to find covariates that might be important to include in regression
#' @param x List generated by the getData function
#' @param response Column header your response of interest in info file (i.e."Disease")
#' @param method Intended regression method.  Supports all base glm methods. (i.e. "gaussian", "binomial", "poisson" etc.)
#' @param direction Direction for step function.  Can be "backwards", "forwards", or "both".  Defaults to both
#' @return Returns a vector of infoFile variables likely to be important in a model
#' @export

findPredictors<-function(x, response, method, direction="both"){
  #create formula for Null Model
  nullFormula<- formula(paste(response, "~1", sep=""))
  #create null model for step function
  nullModel<-glm(nullFormula, family = method, data = x[[1]])
  #create full model formula for step function
  fullFormula<- formula(paste(response, "~.", sep=""))
  #creat full model for step function
  fullModel<-glm(fullFormula, family = method, data=x[[1]])
  #run step function from null model to full model to find optimum covariates based on AIC (we can tweak this)
  step<-step(nullModel, scope = list(lower=nullModel, upper=fullModel), direction=direction, trace=F)
  #return names of useful covariates (we might want to consider return p-values/coefficients too)
  return(names(step$coef[-1]))
}
